services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:8080"
    restart: unless-stopped
    depends_on:
      - postgresdb
    environment:
      API_PORT: ${API_PORT}
    networks:
      - backend

  postgresdb:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - postgresdb_volume:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgresdb_volume:

networks:
  backend: