services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8080"
    restart: unless-stopped
    depends_on:
      - psql_bp
    environment:
      API_PORT: ${PORT}
    networks:
      - backend

  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${BLUEPRINT_DB_DATABASE}
      POSTGRES_USER: ${BLUEPRINT_DB_USERNAME}
      POSTGRES_PASSWORD: ${BLUEPRINT_DB_PASSWORD}
    ports:
      - "${BLUEPRINT_DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  psql_volume_bp:

networks:
  backend: